# Generated by Django 6.0.5 on 2026-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('pop', 'Поп'), ('jazz', 'Джаз'), ('rock', 'Рок'), ('electronic', 'Электроника')], default='pop', max_length=20, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото (из интернета)'),
        ),
    ]
